routes/web.php
<?php

use Catalog\Http\Controllers\CartController;
use Catalog\Http\Controllers\CatalogCategoryController;
use Catalog\Http\Controllers\CatalogFilterCategoryController;
use Catalog\Http\Controllers\CatalogFilterController;
use Catalog\Http\Controllers\CatalogProductController;
use Catalog\Http\Controllers\CatalogYmlController;
use Catalog\Http\Controllers\CatalogSettingsController;
use Catalog\Http\Controllers\CatalogOrderController;
use Catalog\Http\Controllers\RouterController;
use Catalog\QueryBuilder\CatalogBuilder;
use Catalog\Http\Controllers\CatalogPromocodeController;
use Illuminate\Support\Facades\Route;


Route::middleware('web')->group(function (){
    Route::middleware('key_cart')->group(function(){
        Route::middleware('auth_pacage')->group(function () {
            Route::group(['prefix'=>"admin", 'as'=>'admin.', 'middleware' => 'is_admin'],static function(){
                Route::get("catalog", [config('catalog.start_menu'),'index'])
                    ->name("catalog")
                    ->middleware('menu.check:1001');
                Route::group(['prefix' => 'catalog', 'as' => 'catalog.'], static function() {
                    Route::resource('product', CatalogProductController::class);
                    Route::resource('category', CatalogCategoryController::class);
                    Route::resource('settings', CatalogSettingsController::class);
                    Route::resource('yml', CatalogYmlController::class);
                    Route::resource('filter', CatalogFilterController::class);
                    Route::resource('promocode', CatalogPromocodeController::class);
                    Route::resource('filter_category', CatalogFilterCategoryController::class);
                    Route::post('filter_category/order', [CatalogFilterCategoryController::class,'order'])->name('filter_category.order');
                    Route::post('filter/order', [CatalogFilterController::class,'order'])->name('filter.order');
                    Route::post('category/order', [CatalogCategoryController::class,'order'])->name('category.order');
                    Route::post('product/order', [CatalogProductController::class,'order'])->name('product.order');
                    Route::get('category/publish/{category}', [CatalogCategoryController::class,'publish'])->name('category.publish');
                    Route::delete('category/delete_image/{category}/{image}', [CatalogCategoryController::class,'deleteImageCategory'])->name('category.delete_image');
                    Route::get('product/publish/{product}', [CatalogProductController::class,'publish'])->name('product.publish');
                    Route::post('product/{product}/property/add',[CatalogProductController::class,'propertyCreate'])->name('property.add');
                    Route::post('product/{product}/property/order', [CatalogProductController::class,'propertyOrder'])->name('property.order');
                    Route::post('product/{product}/property/{property}/edit', [CatalogProductController::class,'propertyEdit'])->name('property.edit');
                    Route::delete('product/{product}/property/{property}/delete', [CatalogProductController::class,'propertyDelete'])->name('property.delete');
                    Route::put('product/{product}/property/save', [CatalogProductController::class,'propertySave'])->name('property.save');
                });
            });
        });
        try {
            $catalogBuileder = new CatalogBuilder();
            $settings = $catalogBuileder->getCatalogRouter();
            if(config('catalog.swich_category')){
                Route::get($settings['url'],[RouterController::class,"index"])->name("catalog");
            }else{
                Route::get($settings['url'],[RouterController::class,"allProduct"])->name("catalog");
            }
            Route::group(['prefix'=>$settings['url'], 'as'=>'catalog.'],static function(){
                Route::get("/{category}",[RouterController::class,'category'])->name('category');
                Route::get("{category}/filters/{filters}",[RouterController::class,'filters'])
                    ->where('filters', '.*')->name('category.filters');
                Route::get("/{category}/{product}",[RouterController::class,'product'])->name('product');

                Route::get("/{category}/{product}/{article}",[RouterController::class,'product'])->name('product.property');
            });
//            price-to-{price_to}-from-{price_from}/stones:{stones}/colors:{colors}/sort:{sort}
//            price-to-1-from-1000/stones:agat/colors:red/sort:asc
            Route::get("/cart",[RouterController::class,'cart'])->name('cart');
            Route::get("/search",[RouterController::class,'search'])->name('search');
            Route::post("/search",[RouterController::class,'searchItem']);

            Route::group(['prefix'=>"cart"],static function(){
                Route::post('/delete',[CartController::class,'delete']);
                Route::post('/add',[CartController::class,'add']);
                Route::post('/remove',[CartController::class,'remove']);
                Route::post('/delete_all',[CartController::class,'delete_all']);
                Route::post('/get',[CartController::class,'get']);
                Route::post('/get_count',[CartController::class,'get_count']);
                Route::post('/order_click',[CatalogOrderController::class,'click']);
                Route::post('/order',[CatalogOrderController::class,'store']);
            });
        } catch (Exception $exception)
        {

        }
    });
});

resources/views/catalog/category/create.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Добавить категорию</h3>

        </div>
        <x-admin.navigation_list.navigatin-js :links="$navigation" />
        <div class="card-body">
            <x-warning />
            <form action="{{ route('admin.catalog.category.store') }}" enctype="multipart/form-data" method="post" class="row row-page-create">
                @csrf
                <div class="tab-content">
                    <x-catalog::create.content />
                    <x-catalog::create.seo />
                    <x-catalog::create.photo />
                </div>
                <div>
                    <input type="submit" value="Сохранить" class="btn btn-success btn-sm">
                </div>
            </form>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog.category.index")}}">Список категорий</a></li>
            <li class="breadcrumb-item active" aria-current="page">Добавить категорию</li>
        </ol>
    </div>
@endsection

resources/views/catalog/category/edit.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Редактировать категорию</h3>
        </div>
        <x-admin.navigation_list.navigatin-js :links="$navigation" />
        <div class="card-body">
            <x-warning />
            <form action="{{ route('admin.catalog.category.update',['category'=>$category]) }}" enctype="multipart/form-data" method="post" class="row row-page-create">
                @csrf
                @method('PUT')
                <input type="hidden" value="{{$category->id}}" name="id">
                <div class="tab-content">

                    <x-catalog::edit.content :category="$category" />
                    <x-catalog::edit.seo :category="$category" />
                    <x-catalog::edit.photo :category="$category" />
                </div>
                <div>
                    <input type="submit" value="Сохранить" class="btn btn-success btn-sm">
                </div>
            </form>
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog.category.index")}}">Список категорий</a></li>
            <li class="breadcrumb-item active" aria-current="page">Редактировать категорию</li>
        </ol>
    </div>
@endsection

resources/views/catalog/category/index.blade.php
@extends('layouts.admin')
@section('title', 'Каталог')
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header d-flex justify-content-between flex-wrap gap-2">
            <h3 class="card-title">Список категорий</h3>
            <a href="{{ route('admin.catalog.category.create') }}" class="btn btn-primary"><i
                    class="fas fa-plus me-1"></i>Добавить категорию</a>
        </div>
        <div class="card-body">
            <x-warning />
            <div class="row row-page-create">
                <div class="col-md-8 order-md-first">
                    <div class="dd nestable" id="nestable">
                        <x-catalog::category :categories="$categories" />
                    </div>
                </div>

            </div>
        </div>
    </div>
    <input type="hidden" id="route_dd" value="{{ route('admin.catalog.category.order') }}">
    <script src="{{ asset('assets/js/admin/dnd.js') }}"></script>
    <script src="{{ asset('assets/js/admin/delete.js') }}"></script>
    <script src="{{ asset('assets/js/admin/show.js') }}"></script>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.catalog') }}">Каталог</a></li>
            <li class="breadcrumb-item active" aria-current="page">Список категорий</li>
        </ol>
    </div>
@endsection

resources/views/catalog/filter/filter.blade.php
@extends('layouts.admin')
@section('title',config('catalog.menu_links')[\Catalog\Enums\CatalogEnums::FILTER->value]['name'])
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header d-flex justify-content-between align-items-center">
            <h3 class="card-title">Категория: {{ $category->name }}</h3>
            <a class="btn btn-info btn-sm" href="{{ route('admin.catalog.filter.index') }}">Назад</a>
        </div>
        <div class="card-body">
            <x-warning />
            <x-catalog::filter.filter :category="$category" />
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog.filter.index")}}">{{ config('catalog.menu_links')[\Catalog\Enums\CatalogEnums::FILTER->value]['name'] }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Категории</li>
        </ol>
    </div>
@endsection

resources/views/catalog/filter/index.blade.php
@extends('layouts.admin')
@section('title',config('catalog.menu_links')[\Catalog\Enums\CatalogEnums::FILTER->value]['name'])
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Категории</h3>
        </div>
        <div class="card-body">
            <x-warning />
            <x-catalog::filter.category />
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ config('catalog.menu_links')[\Catalog\Enums\CatalogEnums::FILTER->value]['name'] }}</li>
        </ol>
    </div>
@endsection

resources/views/catalog/front/cart.blade.php
@extends('layouts.inner')
{{-- @section('title',$seo_title)
@section('description',$seo_description)
@section('keywords',$seo_keywords) --}}
@section('page',true)
@section('content')
<div class="content">
    <div class="cart">
        <div class="container">
            {{-- <x-front.breadcrumbs :breadcrumbs="$breadcrumbs" flag='true' /> --}}
            <h1>{{ $title }}</h1>
            <div class="cart__wrapper">
                <x-catalog::front.cart/>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/catalog/front/category.blade.php
@extends('layouts.inner')
@section('title',$seo_title)
@section('description',$seo_description)
@section('keywords',$seo_keywords)
@section('page',true)
@section('content')
<div class="content">
    <div class="catalog__container">
        <div class="container">
            <x-front.elements.breadcrumbs :breadcrumbs="$breadcrumbs" flag='true' />
            <h1>{{ $title }}</h1>
            <div class="catalog @if (!empty($filter)) catalog__wrapper-filter @endif">
                <div class="main">
                    <div class="catalog__wrapper">

                        <x-catalog::front.category :categories="$catalog['categories']" />
                    </div>
                </div>
                @if(!empty($filter))
                    <x-catalog::front.filter />
                @endif
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/catalog/front/category_product.blade.php
@extends('layouts.inner')
@section('title',$seo_title)
@section('description',$seo_description)
@section('keywords',$seo_keywords)
@section('page',true)
@section('content')
    <div class="content">
        <div class="catalog__container">
            <div class="container">
                {{-- @dd($breadcrumbs) --}}
                <x-front.breadcrumbs :breadcrumbs="$breadcrumbs"/>
                <h1>{{ $title }}</h1>
                <div class="catalog @if (!empty($filter)) catalog__wrapper-filter @endif">
                    <div class="main">
                        <div class="preloader-container d-none">
                            <div class="spinner"></div>
                        </div>
                        <div class="catalog__wrapper-products-container">
                            <x-catalog::front.product :products="$catalog['products']" :path="!empty($path) ? $path : '/catalog/category/'" :url="$url" />
                            {!! $category->description !!}
                        </div>
                    </div>
                    @if(!empty($filter))
                        <x-catalog::front.filter :category="$category" />
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/catalog/front/product.blade.php
@extends('layouts.inner')
 @section('title',$seo_title)
@section('description',$seo_description)
@section('keywords',$seo_keywords)
@section('page',true)
@section('content')
<div class="content">
    <div class="container">
        <x-front.elements.breadcrumbs :breadcrumbs="$breadcrumbs" flag='true' />
        <div class="card--box">
            <h1>{{ $product->title }}</h1>
            <x-catalog::front.product_info :product='$product'/>
            <x-catalog::front.product_desc :product='$product'/>
            <x-catalog::front.product_popular :popular="$popular" :popularAll="$popularAll" />
            <x-catalog::front.modal/>
        </div>
    </div>

</div>

@endsection

resources/views/catalog/front/search.blade.php
@extends('layouts.inner')
@section('title',$seo_title)
@section('description',$seo_description)
@section('keywords',$seo_keywords)
@section('page',true)
@section('content')
    <div class="content">
        <div class="container">
            <div class="form-groop">
                <label for="search">Поиск</label>
                <input type="text" id="search" class="form-control">
            </div>
            <div id="search_container" class="catalog__wrapper-products">
{{--                <div class="catalog__product__item">--}}
{{--                    <a href="{{ route('catalog.product',['product'=>$product->url]) }}" class="img-container">--}}
{{--                        @if ($product->images)--}}
{{--                            <img src="{{ $product->images[0] }}" alt="{{ $product->title }}">--}}
{{--                        @else--}}
{{--                            <img src="{{ asset('assets/img/no-image.png') }}" class="contain" alt="{{ $product->title }}">--}}
{{--                        @endif--}}
{{--                    </a>--}}
{{--                    <a href="{{ route('catalog.product',['product'=>$product->url]) }}" class="title-container">--}}
{{--                        <h4 class="title">{{ $product->title }}</h4>--}}
{{--                    </a>--}}
{{--                    <div class="weight">--}}
{{--                        <p>Толщина: <span>200</span> мк</p>--}}
{{--                    </div>--}}
{{--                    <div class="price">--}}
{{--                        <p><span>{{ $product->price }}</span>/пог. м</p>--}}
{{--                    </div>--}}
{{--                    <button class="button button-s popular__btn add_cart" data-product="" data-id="{{ $product->id }}">--}}
{{--                        <span>в корзину</span>--}}
{{--                    </button>--}}
{{--                </div>--}}
            </div>
        </div>
    </div>
    <input type="hidden" value="{{ $url }}" id="url">
    <x-catalog::front.templItem />
    @vite('resources/js/catalog/searchProduct.js')
@endsection

resources/views/catalog/order/index.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Список заказов</h3>
        </div>
        <div class="card-body">
            <x-catalog::order />
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item active" aria-current="page">Список заказов</li>
        </ol>
    </div>
@endsection

resources/views/catalog/product/create.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Добавить товар</h3>
        </div>
        <x-admin.navigation_list.navigatin-js :links="$navigation" />
        <div class="card-body">
            <x-warning />
            <form action="{{ route('admin.catalog.product.store') }}" enctype="multipart/form-data" method="post" class="row row-page-create">
                @csrf
                <div class="tab-content">
                    <x-catalog::product.create.content />
                    <x-catalog::product.create.seo />
                    <x-catalog::product.create.photo />
                </div>
                <div>
                    <input type="submit" value="Сохранить" class="btn btn-success btn-sm">
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/catalog/product/edit.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Редактировать товар</h3>
        </div>
        <x-admin.navigation_list.navigatin-js :links="$navigation" />
        <div class="card-body">
            <x-warning />
            <form action="{{ route('admin.catalog.product.update',['product'=>$product]) }}" enctype="multipart/form-data" method="post" class="row row-page-create">
                @csrf
                @method('PUT')
                <input type="hidden" value="{{$product->id}}" name="id">
                <div class="tab-content">
                    <x-catalog::product.edit.content :product="$product" />
                    <x-catalog::product.edit.property :product="$product" />
                    <x-catalog::product.edit.seo :product="$product" />

                    <x-catalog::product.edit.photo :product="$product" />
                </div>
                <div>
                    <input type="submit" value="Сохранить" class="btn btn-success btn-sm">
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/catalog/product/index.blade.php
@extends('layouts.admin')
@section('title', 'Каталог')
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header d-flex justify-content-between flex-wrap gap-2">
            <div>
                <h3 class="card-title">Товары</h3>
            </div>
            <div class="d-flex justify-content-between flex-wrap gap-2">
                <a data-id="1" data-name="text" class="btn  search modal-effect btn-warning" data-bs-effect="effect-fall"
                    data-bs-toggle="modal" data-bs-target="#modaldemo8" type="button">Поиск</a>
                <a href="{{ route('admin.catalog.product.create') }}" class="btn btn-primary">
                    <i class="fas fa-plus me-1"></i>Добавить позицию
                </a>
            </div>
        </div>
        <div class="card-body">
            <x-catalog::product.index />
        </div>
    </div>
    <x-admin.modal title="Поиск" id="search" />
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <x-catalog::product.seach />
    @vite('resources/js/catalog/search.js')
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Каталог</li>
        </ol>
    </div>
@endsection

resources/views/catalog/product/show.blade.php
@extends('layouts.admin')
@section('title', 'Каталог')
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header d-flex justify-content-between">
            <h3 class="card-title">Товары</h3>
            <div>
                <a data-id="1" data-name="text" class="btn btn-sm search modal-effect btn-warning badge"
                    data-bs-effect="effect-fall" data-bs-toggle="modal" data-bs-target="#modaldemo8" type="button">Поиск</a>
                <a href="{{ route('admin.catalog.product.create') }}" class="btn btn-sm btn-outline-primary">
                    <small>Добавить позицию</small>
                </a>
            </div>
        </div>
        <div class="card-body">
            <x-warning />
            <input type="hidden" id="category" value="{{ $category }}">
            <div class="row row-page-create">
                @if (count($categories) > 0)
                    <div class="col-lg-6">
                        <label>Категории</label>
                        <x-catalog::product.category :categories="$categories" />
                    </div>
                @endif
                <div class="col-lg-6">
                    <label>Товары</label>
                    <div class="dd nestable" id="nestable">
                        <x-catalog::product.list :products="$products" :category="$category" />
                    </div>
                </div>

            </div>
        </div>
    </div>
    <input type="hidden" id="route_dd" value="{{ route('admin.catalog.product.order') }}">
    <script src="{{ asset('assets/js/admin/delete.js') }}"></script>
    <x-admin.modal title="Поиск" id="search" />
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <x-catalog::product.seach />
    @vite('resources/js/catalog/search.js')
    @vite('resources/js/catalog/productDnd.js')
    <script src="{{ asset('assets/js/admin/show.js') }}"></script>
@endsection

@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Главная</a></li>
            @if (count($breadcrumb) > 0)
                <li class="breadcrumb-item"><a href="{{ route('admin.catalog.product.index') }}">Каталог</a></li>
                @foreach ($breadcrumb as $item)
                    @if (!$loop->last)
                        <li class="breadcrumb-item"><a href="{{ $item['url'] }}">{{ $item['title'] }}</a></li>
                    @else
                        <li class="breadcrumb-item active" aria-current="page">{{ $item['title'] }}</li>
                    @endif
                @endforeach
            @else
                <li class="breadcrumb-item active" aria-current="page">Каталог</li>
            @endif
        </ol>
    </div>
@endsection

resources/views/catalog/promocode/index.blade.php
@extends('layouts.admin')
@section('title',"Промокоды")
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Промокоды</h3>

        </div>
        <div class="card-body">
            <x-warning />
            <div class="row">
                <div class="col-8">
                    <x-catalog::promocode.list />
                </div>
                <div class="col-4">
                    <x-catalog::promocode.add />
                </div>
            </div>

        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item active" aria-current="page">Проиокоды</li>
        </ol>
    </div>
@endsection

resources/views/catalog/settings/index.blade.php
@extends('layouts.admin')
@section('title',"Настройки")
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">Настройки</h3>

        </div>
        <div class="card-body">
            <x-catalog::settings />
        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item active" aria-current="page">Настройки</li>
        </ol>
    </div>
@endsection

resources/views/catalog/yml/index.blade.php
@extends('layouts.admin')
@section('title',"Каталог")
@section('content')
    <div class="card">
        <x-admin.navigation_list.navigation :links="$links" />
        <div class="card-header">
            <h3 class="card-title">YML</h3>
        </div>
        <div class="card-body">
            <x-warning />
            <div class="row">
                <div class="col-lg-24">
                    @if($settings)
                        <p class="ml-4">
                            Файл сгенерирован: <strong>{{ $settings->updated_at->format('d.m.Y H:i') }}</strong>
                        </p>
                    @endif
                    <a href="{{ route('admin.catalog.yml.create') }}" class="btn btn-orange btn-sm">Сгенирировать</a>
                </div>
                @if($settings)
                    <div class="col-lg-6">
                        <div class="choose-file d-flex align-items-center mt-4">
                            <a download="products.yml" href="/products.yml">
                            <i class="fas fa-file-download" style="font-size: 22px; color: #28a745!important"></i>
                            </a>
                            <input id="link_filed" name="link" type="text" class="form-control form-control-sm mx-3" value="{{ env("APP_URL") }}/products.yml" placeholder="{{ env("APP_URL") }}/products.yml">
                        </div>
                    </div>
                @endif
            </div>


        </div>
    </div>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{route("admin.catalog")}}">Каталог</a></li>
            <li class="breadcrumb-item active" aria-current="page">YML</li>
        </ol>
    </div>
@endsection